### ISSUE TITLE
multi-draw issue

### ISSUE THREAD

**Issue by wwavelet** [saadq/scramby#1]
It will append <svg/> instead of replace it if we draw many  times?
```
import scramby from 'scramby'
const scrambler = scramby()
 
const { state } = scrambler.getRandomScramble()
scrambler.drawScramble(document.getElementById('my-el'), state, 300, 180);
...
 //draw 2 times and got 2 <svg/>
scrambler.drawScramble(document.getElementById('my-el'), state, 300, 180);
```
So if I want replace it,  I must clear it like below?
```
let my-el = document.getElementById('my-el');
my-el.innerHTML = '';
scrambler.drawScramble(document.getElementById('my-el'), state, 300, 180);
```

**Comment by saadq** [comment]
Ah yes, it looks like that might be the case. I inherited all the draw code from `jsss`, and haven't really touched that part of it, but I believe it should be an easy fix. I should have it fixed by today. Thanks for bringing this up. I'll probably just do the clearing within the library so that the user doesn't have to do it themselves.

**Comment by saadq** [comment]
Alright, I've updated the package on GitHub as well as npm, this issue should be fixed now. Please reopen if you still face this problem.
